import React, { useEffect, useState } from "react";
import axios from "axios";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

function TransactionList({ refresh }) {
  const [transactions, setTransactions] = useState([]);

  const fetchTransactions = async () => {
    try {
      const res = await axios.get("https://splitsmart-upi.onrender.com/transactions");
      setTransactions(res.data);
    } catch {
      setTransactions([]);
    }
  };

  useEffect(() => {
    fetchTransactions();
  }, [refresh]);

  const downloadReceipt = async (transaction) => {
    const receipt = document.createElement("div");

    receipt.innerHTML = `
      <div style="
        width: 380px;
        padding: 25px;
        font-family: Arial, sans-serif;
        background: white;
        color: black;
        border-radius: 12px;
      ">
        <h2 style="text-align:center;color:#0077ff;">🚀 SplitSmart UPI Receipt</h2>
        <hr />
        <h1 style="text-align:center;color:green;">₹${transaction.amount}</h1>
        <p><b>Sender:</b> ${transaction.sender}</p>
        <p><b>Receiver:</b> ${transaction.receiver}</p>
        <p><b>Receiver UPI:</b> ${transaction.receiver_upi}</p>
        <p><b>Note:</b> ${transaction.note}</p>
        <p><b>Date & Time:</b> ${transaction.time}</p>
        <hr />
        <p style="text-align:center;font-size:12px;color:gray;">
          Generated by SplitSmart UPI
        </p>
      </div>
    `;

    receipt.style.position = "absolute";
    receipt.style.left = "-9999px";
    document.body.appendChild(receipt);

    const canvas = await html2canvas(receipt);
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");
    const width = 190;
    const height = (canvas.height * width) / canvas.width;

    pdf.addImage(imgData, "PNG", 10, 10, width, height);
    pdf.save(`SplitSmart_Receipt_${transaction.id}.pdf`);

    document.body.removeChild(receipt);
  };

  return (
    <div className="card">
      <h2>📜 Transaction History</h2>

      {transactions.length === 0 && <p>No transactions yet</p>}

      {transactions.map((t) => (
        <div className="transaction" key={t.id}>
          <h3>₹{t.amount}</h3>
          <p>
            <b>{t.sender}</b> → <b>{t.receiver}</b>
          </p>
          <p>UPI: {t.receiver_upi}</p>
          <p>{t.note}</p>
          <small>{t.time}</small>
          <br />

          <button onClick={() => downloadReceipt(t)}>
            ⬇️ Download Receipt PDF
          </button>
        </div>
      ))}
    </div>
  );
}

export default TransactionList;